eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761//eureka
server:
  port: 8080
spring:
  application:
    name: Registation
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/se
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  management:
   endpoint:
    web:
      exposure:
        include:'*' 

    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 266MB
